version: '3'
services:
  acunetix:
    build: .
    restart: always
    ports:
      - "443:3443"
    image: acu1345
    volumes:
        - /home/acunetix/.acunetix/data/scans:/home/acunetix/.acunetix/data/scans
        - /home/acunetix/.acunetix/data/targets:/home/acunetix/.acunetix/data/targets
